name: tmt
description: A Very Good Project created by Very Good CLI.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  args: ^2.3.1
  cli_completion: ^0.2.0
  mason_logger: ^0.2.4
  pub_updater: ^0.2.4
  very_good_cli: ^0.14.0
  code_builder: ^4.4.0
  collection: ^1.17.1
  built_collection:
  dart_style: ^2.2.5
  tmt_dart_utils:
    git:
      path: packages/tmt_dart_utils
      url: https://github.com/namhi/tmt_flutter_utils.git
      ref: master
  process_run: ^0.12.5+2
dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0

executables:
  tmt: main
